### ISSUE TITLE
error: dicegroup/halyard-webapps not found

### ISSUE THREAD

**Issue by seralf** [dice-group/docker-halyard#3]
Hi trying to build following the instructions, I get the following error:

```
...
Pulling halyard (dicegroup/halyard-webapps:1.0.0-halyard1.2)...
ERROR: repository dicegroup/halyard-webapps not found: does not exist or no pull access
```
I tried to having the image built locally, changing this in part in my `docker-compose-standalone.yml`:

```
  halyard:
    #image: dicegroup/halyard-webapps:1.0.0-halyard1.2
    build: ./webapps
    container_name: halyard
```
and the image was indeed build, even if I still cannot connect to the webapp, but it could be some misconfiguration in my local port mapping.

do you have any advice? (thanks in advance)
